### ISSUE TITLE
panic when Session::handshake on Windows 10 1903

### ISSUE THREAD

**Issue by kkua** [alexcrichton/ssh2-rs#122]
My program paniced when execute Session::handshake on windows 10 1903, the error message says 
> Error { code: -13, msg: "socket disconnect" }

It didn't panic on the previous Windows version such as win10 1809, win7 and so on. I'm using stable-x86_64-pc-windows-gnu toolchain.

**Comment by wez** [comment]
Do you have access to the logs on the ssh server side?  If so, try running this command; here's what I'm seeing when I connect from windows to my ubuntu host:

```
$ sudo grep kex /var/log/auth.log
Jul 30 16:53:23 nuc sshd[9240]: error: kex protocol error: type 5 seq 2 [preauth]
```

The issue I'm seeing, and that sounds like it my be the same as what you're hitting, is due to this issue with the upstream libssh2 library when it is built against the Windows CNG library (the default for the `ssh2` crate on windows):

https://github.com/libssh2/libssh2/issues/388

I had slightly better luck when I installed `vcpkg` and used that to install `libssh2`, but I ran into some other issues.

**Comment by kkua** [comment]
I tried to check the `/var/log/secure` log file of server which use CentOS 6, it says:
```
 Jul 31 11:41:57 localhost sshd[2854]: Disconnecting: Protocol error: expected packet type 32, got 5
```

**Comment by wez** [comment]
That's consistent with the error reported in the original comment on https://github.com/libssh2/libssh2/issues/388

**Comment by wez** [comment]
I have a PR open against libssh2 that resolves this for me, and that we could fold in to our bundled fork of libssh2.  Let's see what feedback we get from the PR review before we do that.

In the meantime, the workaround is to install `vcpkg` and then `vcpkg install libssh2` to get a build that uses openssl instead of wincng.

**Comment by wez** [comment]
0.4.0 has just been published to crates.io!

**Comment by baysmith** [comment]
Note: if you encounter this problem, the openssl-on-win32 feature might be a workaround.
(At least it was for me.)
