### ISSUE TITLE
How to create an interactive ssh shell to remote host?

### ISSUE THREAD

**Issue by knightflower1989** [alexcrichton/ssh2-rs#128]
How to create an interactive ssh shell to remote host?

**Comment by wez** [comment]
Something like this:

```
use std::io::prelude::*;
use std::net::{TcpStream};
use ssh2::Session;

// Connect to the local SSH server
let tcp = TcpStream::connect("127.0.0.1:22").unwrap();
let mut sess = Session::new().unwrap();
sess.set_tcp_stream(tcp);
sess.handshake().unwrap();
sess.userauth_agent("username").unwrap();

let mut channel = sess.channel_session().unwrap();
// See https://docs.rs/ssh2/0.4.0/ssh2/struct.Channel.html#method.request_pty
channel.request_pty(
   "xterm",
    None,
    Some((80, 24, 0, 0)),)),
).unwrap();

// Run the user's shell.  Alternatively, use channel.exec() to run a specific command
channel.shell().unwrap();

// Now you can read/write the channel to interact with the shell
```

**Comment by knightflower1989** [comment]
How many times should i read from the channel  when call write function?

write "ls -l"  need to read twice.

write "pwd" just to need read once.

or sleep for a while to wait remote data before read .

is any cool way to handle this situation?

**Comment by accounttopostissue** [comment]
I am unable to read from the channel after authenticating and starting shell.
I should be able to read the prompt at least, but reading just hangs.
Tried against two different hosts running two different ssh daemons, both v2.

**Comment by accounttopostissue** [comment]
@wez : The following fails to read a response:

````
#[cfg(test)]
mod tests {
  use std::io::prelude::*;
  use std::net::{TcpStream};
  use ssh2::Session;

  #[test]
  fn ls(){
    let tcp = TcpStream::connect(("127.0.0.1", 22)).unwrap();
    let mut sess = Session::new().unwrap();
    sess.set_tcp_stream(tcp);
    sess.handshake().unwrap();
    sess.userauth_password("user", "password")).unwrap();
    println!("Connected");

    let mut channel = sess.channel_session().unwrap();
    let mut s = String::new();

    channel.request_pty(
     "xterm",
      None,
      Some((80, 24, 0, 0))
    ).unwrap();

    channel.shell().unwrap();

    channel.write(b"ls\n").unwrap();
    match channel.read_to_string(&mut s) {
      Ok(c) => { println!("Read {} bytes: {}", c, s); }
      Err(e) => { println!("Error while reading: {}", e); }
    }
    channel.wait_close();
    println!("{}", channel.exit_status().unwrap());
  }
}
````

FWIW, `channel.exec("ls").unwrap();` does work. But this issue is about an interactive shell.

**Comment by wez** [comment]
`read_to_string` attempts to read until it reaches EOF but EOF is never received: the shell session is still alive because it is waiting for input; you effectively have the classic logical deadlock that is common when trying to manage interactive child processes.

Instead, you want something like this:

```rust
    channel.shell().unwrap();

    // send the command and then exit the shell so that
    // it closes the stream when it is done
    channel.write(b"ls\nexit\n").unwrap();

    // repeatedly read some data and treat it as utf-8.
    // This isn't sufficient for a real interactive session because you will receive
    // partial buffers that are incomplete utf-8 and you'll want to properly buffer
    // them up and decode them, but this is good enough for a basic demo
    loop {
        let mut buf = [0u8; 1024];

        match channel.read(&mut buf) {
            // the channel has closed and we got an EOF
            Ok(0) => break,
            // We got some data; try to decode it as utf-8
            Ok(c) => {
                let slice = &buf[0..c];
                match std::str::from_utf8(slice) {
                    Ok(s) => print!("{}", s),
                    Err(e) => {
                        // TODO: you should buffer this up and try to stick it together
                        // with the next chunk of data that you read later on
                        eprintln!("output was not utf8: {}", e);
                        break;
                    }
                }
            }
            Err(e) => {
                println!("Error while reading: {}", e);
                break;
            }
        }
    }
    channel.wait_close().unwrap();
    println!("{}", channel.exit_status().unwrap());
```

**Comment by accounttopostissue** [comment]
How can you write, read, write, read, etc. without having to close and open channels repeatedly?

In the example above, I can't read the response to `channel.write(b"ls\n")`. I don't get a response until I `write(b"exit\n")`.

Say, for example, I want to delete the file with the most characters in its name. So I want to `ls`, process the results, then `rm`. I don't want to have to exit, then acquire a new channel in between the `ls` and the `rm`.

**Comment by anowell** [comment]
I'm not following along closely here, but I had subscribed when I was battling through this. I didn't end up using my solution, but I did get the basics of an interactive shell working. Hopefully this helps a bit.

Note - this uses some functionality from `termion` for convenience:
- [termion::raw::IntoRawMode](https://docs.rs/termion/1.5.3/termion/raw/trait.IntoRawMode.html) - avoids double echo of content typed into shell
- [termion::async_stdin](https://docs.rs/termion/1.5.3/termion/fn.async_stdin.html) - manages stdin in a separate thread to enable reading it without blocking the current thread.

```
        if sess.authenticated() {
            let mut channel = sess.channel_session()?;

            channel.request_pty("xterm", None, None).unwrap();
            channel.handle_extended_data(ssh2::ExtendedData::Merge);
            channel.shell()?;

            let stdout = io::stdout();
            let mut stdout = stdout.lock().into_raw_mode().unwrap();
            let mut stdin = async_stdin();

            let mut buff_in = Vec::new();
            while !channel.eof() {
                let bytes_available = channel.read_window().available;
                if bytes_available > 0 {
                    let mut buffer = vec![0; bytes_available as usize];
                    channel.read_exact(&mut buffer)?;
                    stdout.write(&buffer)?;
                    stdout.flush()?;
                }

               // Using async_stdin to avoid blocking, should this also respect the WriteWindow?
                stdin.read_to_end(&mut buff_in)?;
                channel.write(&buff_in)?;
                buff_in.clear();

                // Unsure of best practice, but this feels responsive and avoids pegging the CPU 
                std::thread::sleep(std::time::Duration::from_millis(50));
            }
            channel.wait_close()?;
        }
```

I ultimately abandoned this code because I quickly found myself in the weeds toward reinventing the shell functionality of `ssh` with limited time and understanding:

- How can I reliably drop the server's banner?
- How can I reliably send initial commands to configure the remote shell (my original attempt would appear in the banner, and hadn't dug in enough to know the "right" way/time to send them)
- How would I support `ProxyCommand` (to proxy through a netcat tunnel)
- Do SSH shells normally merge stdout/stderr?

So for now, I've resorted to shelling out to `ssh`, and just kept this snippet around in case I ever make time for contributing to a more complete interactive SSH shell abstraction.

**Comment by knightflower1989** [comment]
Simple interactive ssh shell to my vagrant host.

`
extern crate crossbeam;

use crossbeam::channel::{unbounded, TryRecvError};
use ssh2::Session;
use std::io::prelude::*;
use std::net::TcpStream as StdTcpStream;
use std::thread;

fn main() {
    let tcp = StdTcpStream::connect("192.168.33.30:22").unwrap();
    let mut sess = Session::new().unwrap();
    sess.set_tcp_stream(tcp);
    sess.handshake().unwrap();
    sess.userauth_password("root", "vagrant").unwrap();

    let mut channel = sess.channel_session().unwrap();

    channel.request_pty("xterm", None, None).unwrap();

    channel.shell().unwrap();

    sess.set_blocking(false);

    let (trx, rev) = unbounded();

    thread::spawn(move || loop {
        let stdin = std::io::stdin();
        let mut line = String::new();
        stdin.read_line(&mut line).unwrap();
        trx.send(line).unwrap();
    });

    loop {
        let mut buf = vec![0; 4096];
        match channel.read(&mut buf) {
            Ok(_) => {
                let s = String::from_utf8(buf).unwrap();
                println!("{}", s);
            }
            Err(e) => {
                if e.kind() != std::io::ErrorKind::WouldBlock {
                    println!("{}", e);
                }
            }
        }

        if !rev.is_empty() {
            match rev.try_recv() {
                Ok(line) => {
                    let cmd_string = line + "\n";
                    channel.write(cmd_string.as_bytes()).unwrap();
                    channel.flush().unwrap();
                }

                Err(TryRecvError::Empty) => {
                    println!("{}", "empty");
                }

                Err(TryRecvError::Disconnected) => {
                    println!("{}", "disconnected");
                }
            }
        }
    }
}
`

this can execute command interactively and print remote stdout.

some hints to command completion by Tab key ?

**Comment by anowell** [comment]
@knightflower1989 The key to supporting tab completion is actually sending the tab character to the remote channel (remote shell is doing the completion), capturing the channel output (which includes control characters to properly print the tab completion), then writing that to stdout. So you can't simply read stdin line-by-line (`read_line`), because currently you'd only send the tab character after hitting enter.

Then I assume you're seeing double output of the things you interactively enter (I might be missing something), and your `println` is adding a newlines for every response which might affect how the autocomplete renders (the newline would affect the control characters that move the cursor around the way that autocomplete does). Effectively this is where setting stdout in raw_mode is important, to disable echo of what you type locally. That way you capture stdin (byte-by-byte, not line-by-line), send it to the remote channel, and print the channel output (which includes the bytes you sent it).

This is what my [previous snippet](https://github.com/alexcrichton/ssh2-rs/issues/128#issuecomment-555296844) does. Sets stdin in raw mode using `termion::raw::IntoRawMode` and uses `termion::async_stdin` to setup the stdin thread like yours, except it isn't limited to reading line-by-line.

**Comment by wez** [comment]
a concrete implementation of a fully interactive ssh session can be found in my terminal emulator (https://wezfurlong.org/wezterm/); there are some additional layers involved there that make it a bit harder to see what is going on, so here are some pointers:

* The `portable_pty` crate implementation in https://github.com/wez/wezterm/tree/master/pty/src (docs at https://docs.rs/portable-pty/0.2.0/portable_pty/) abstracts dealing with a pty/tty for posix, windows, serial ports and ssh sessions
* This file contains session establishment, authentication prompts and the pty setup https://github.com/wez/wezterm/blob/master/src/ssh.rs#L353
* Once established, the read side (obtained via https://docs.rs/portable-pty/0.2.0/portable_pty/trait.MasterPty.html#tymethod.try_clone_reader) is spawned into a thread that is dedicated to reading the output from the peer and running it through the escape sequence parser and feeding the output to the terminal model: https://github.com/wez/wezterm/blob/master/src/mux/mod.rs#L48
* Separately from all of that, the UI translates keypresses and writes them to the write side

The key thing to note is that the terminal has no idea about when a command begins or ends; that is known only by whatever is running on the other end of the ssh session, and as a client you have no way to know from the ssh protocol what is going on beyond receiving the output stream and detecting when the stream has terminated, so you'll either need the remote program to co-operate with you (eg: by emitting special marker output that you can match on), or by having your program hard code some matching/scraping logic specific to the task at hand.

**Comment by Timmmm** [comment]
Here is my solution which forwards stdin, stdout, *and* stderr. Some notes:

* Unlike [anowell's solution](https://github.com/alexcrichton/ssh2-rs/issues/128#issuecomment-555296844) it doesn't have any ugly busy loop.
* Unlike [knightflower1989's solution](https://github.com/alexcrichton/ssh2-rs/issues/128#issuecomment-555427750) it doesn't block stdin while reading stdout.
* I haven't thought about what happens when streams are closed, or the SSH channel closes much.
* One of these three channel could probably go on the main thread, but I put all three in separate threads for simplicity and symmetry.
* Some of the `Result` type annotations are unnecessary but I put them in because it gets pretty confusing otherwise!
* Not extensively tested yet!

```
fn execute_and_forward(session: &Session, command: &str) -> anyhow::Result<i32> {
  let mut channel = session.channel_session()?;
  channel.exec(command)?;

  let mut ssh_stdin = channel.stream(0);
  let mut ssh_stdout = channel.stream(0);
  let mut ssh_stderr = channel.stderr();

  let all_result: Result<u64, io::Error> = crossbeam::scope(|s| {
    let stdin_handle = s.spawn(|_| {
      let stdin = io::stdin();
      let mut stdin = stdin.lock();
      io::copy(&mut stdin, &mut ssh_stdin)
    });

    let stdout_handle = s.spawn(|_| {
      let stdout = io::stdout();
      let mut stdout = stdout.lock();
      io::copy(&mut ssh_stdout, &mut stdout)
    });

    let stderr_handle = s.spawn(|_| {
      let stderr = io::stderr();
      let mut stderr = stderr.lock();
      io::copy(&mut ssh_stderr, &mut stderr)
    });

    // The unwrap() means the main thread will panic if the inner threads panicked.
    let stdin_result: Result<u64, io::Error> = stdin_handle.join().unwrap();
    let stdout_result: Result<u64, io::Error> = stdout_handle.join().unwrap();
    let stderr_result: Result<u64, io::Error> = stderr_handle.join().unwrap();

    stdin_result.and(stdout_result).and(stderr_result)
  })
  .unwrap(); // Should never panic because all scoped threads have been joined.

  // Return Err if any of the threads errorred.
  all_result?;

  // Wait for SSH channel to close.
  channel.wait_close()?;
  let exit_status = channel.exit_status()?;
  Ok(exit_status)
}
```

**Comment by wez** [comment]
this comment about blocking on https://github.com/alexcrichton/ssh2-rs/issues/189#issuecomment-640271049 also applies here

**Comment by cq123456a** [comment]
useful

**Comment by psymole** [comment]
I implemented the solution proposed by @anowell.
It works great, but after exit on the remote host, the next character I type is not read by the program.

On first run.
Select index -->'x)' of device to initiate a connection:ssh 12
All characters are read and a connection is made----^^^^^

After SSHing. I get
Select index -->'x)' of device to initiate a connection:12
..............................................character 1 is ignored---^^----character 2 prints and works/fails as expected.

Any Ideas? I'm quite new at rust. So, any pointers would be greatly appreciated.
````
fn start_ssh(index: usize, ipl: &Vec<IpAddr>) {
    if index < ipl.len() {
        let ip = ipl[index];
        let tcp = TcpStream::connect(format!("{}:22", ip)).unwrap();
        let mut sess = Session::new().unwrap();
        sess.set_tcp_stream(tcp);
        sess.handshake().unwrap();
        sess.userauth_password("user", "password").unwrap();

        if sess.authenticated() {
            let mut channel = sess.channel_session().unwrap();

            channel.request_pty("xterm", None, None).unwrap();
            channel
                .handle_extended_data(ssh2::ExtendedData::Merge)
                .unwrap();
            channel.shell().unwrap();

            let stdout = io::stdout();
            let mut stdout = stdout.lock().into_raw_mode().unwrap();
            let mut stdin = async_stdin();

            let mut buff_in = Vec::new();
            while !channel.eof() {
                let bytes_available = channel.read_window().available;
                if bytes_available > 0 {
                    let mut buffer = vec![0; bytes_available as usize];
                    channel.read_exact(&mut buffer).unwrap();
                    stdout.write(&buffer).unwrap();
                    stdout.flush().unwrap();
                }

                // Using async_stdin to avoid blocking, should this also respect the WriteWindow.unwrap()
                stdin.read_to_end(&mut buff_in).unwrap();
                channel.write(&buff_in).unwrap();
                buff_in.clear();

                // Unsure of best practice, but this feels responsive and avoids pegging the CPU
                std::thread::sleep(std::time::Duration::from_millis(50));
            }
            channel.wait_close().ok();
        }
    }
}

    loop {
        // Prints a list of results
        let mut ip_list = Vec::new();
        for (n, (mac, dev)) in result.iter().enumerate() {
            println!();
            println!("{}) Name: {}", n, dev.1);
            println!("Ip: {} | Mac: {}", dev.2, mac);
            ip_list.push(dev.2)
        }
        // grab user choice
        let mut input_cnct = String::new();
        print!("\nSelect index -->'x)' of device to initiate a connection: ");
        io::stdout().flush().expect("Unable to flush stdout");
        io::stdin()
            .read_line(&mut input_cnct)
            .expect("Failed to read line");
        // trim newline character
        let cnct = input_cnct.trim();

        // After exiting ssh connection first charecters in not read.
        print!("choice {} : ", cnct);

        // options for multiple paths
        let choice: Vec<&str> = cnct.split_whitespace().collect();
        if cnct.is_empty() == false {
            match choice[0] {
                "b" => {
                    println!("Slected q");
                    Command::new("clear").status().unwrap();
                    break 'select;
                }
                "ssh" => {
                    if choice.len() != 2 {
                        println!("Must pass exactly two Arguments, 'ssh' and index selection.")
                    } else {
                        println!("sshing to dev # {}", choice[1]);
                        let c: usize = match choice[1].trim().to_string().parse() {
                            Ok(n) => n,
                            Err(_) => continue,
                        };
                        // call ssh function from @anowell
                        start_ssh(c, &ip_list);
                    }
                }
                _ => {
                    let c: usize = match choice[0].trim().to_string().parse() {
                        Ok(n) => n,
                        Err(_) => continue,
                    };
                    start_vnc(c, &ip_list);
                }
            }
        }
    } //end select loop

```

**Comment by anowell** [comment]
@psymole - You lose one character because of you're calling `async_stdin()` more than once and mixing it with `io::stdin()`. If you look at [the implementation of async_stdin](https://docs.rs/termion/1.5.3/src/termion/async.rs.html#40-50), it creates an mpsc channel and then spawns a thread. That thread consumes bytes from the TTY in a loop and sends them to the mpsc channel. The thread loops until the channel send fails (or TTY closes).

So in your scenario, once you exit the remote host, the instance of `AsyncReader` (returned by `async_stdin`) is dropped. That causes the mpsc channel to be dropped and thus closed. But the thread is still waiting for the next byte from the TTY. As soon as the next byte arrives from the TTY (after your prompt), it tries to send it on the mpsc channel, but it fails because the channel is closed. That byte is lost, and the `async_stdin` loop ends so it stops consuming additional bytes from the TTY.

And actually, after the SSH session exits, you have `io::stdin().read_line()` and `async_stdin()` both waiting for input which creates a race condition; it might not always be the first byte that is lost. And it's weird because they aren't even both opening stdin; termio's `async_stdin` is reading `/dev/tty` instead.

Resolving this will require you to rethink usage of stdin/TTY input to ensure you can't ever have a situation where 2 threads are simultaneously waiting for stdin/tty input. A few options:
1. Make all input reading share access to stdin or TTY collected from a single, long-lived thread (e.g. call `async_stdin()` before your main loop, and share that returned instance of `AsyncReader` in both functions to read input).
2. Remove `async_stdin` and use non-blocking IO ([O_NONBLOCK](https://www.man7.org/linux/man-pages/man7/pipe.7.html)) for stdin in `start_ssh` (e.g. [nonblock](https://docs.rs/nonblock/latest/nonblock/)). Then you don't need a separate thread for reading stdin, and each iteration in the SSH session loop just reads whatever is available. [Select](https://www.man7.org/linux/man-pages/man2/select.2.html), [poll](https://www.man7.org/linux/man-pages/man2/poll.2.html), and [epoll](https://man7.org/linux/man-pages/man7/epoll.7.html) are other unix facilities that would similarly enable checking stdin without blocking.
3. Just shell out to `ssh` instead. ☺️

**Comment by anowell** [comment]
@psymole - I'm not sure if I follow your scenario, but openssh does have ControlMaster (`-M`) and ControlPath (`-S`) concepts. I'm not sure how much logic goes into setting up a ControlMaster (is it just a matter of getting the path to the underlying unix socket?), but if you could emulate that in your app, then shelling out could skip auth. But then you probably also have to think through when/how to terminate/timeout the control master.

Or, if it's just a question of shelling out with username/password, `sshpass` may work (which automates password interaction). It seems intentional (and probably wise) that openssh didn't expose a flag for non-interactive password auth, so if you can use public key auth, `-i <identify_file>` is easier to automate.

Hopefully that at least helps you sort through the options and tradeoffs that make sense for your app.

**Comment by Timmmm** [comment]
I have a fair bit of experience using SSH programmatically - for VSCode style remote access rather than an interactive shell - but this is what I've learnt. Might be useful:

* VSCode's remote SSH extension is closed source but I'm pretty sure it basically does `system("ssh ...")`
* For a work project using Electron we used [this library](https://github.com/mscdex/ssh2).
* For a personal project I wrote a simple custom SSH binary using Go (easy to cross-compile and good built in SSH library). I communicate with it over stdin/stdout using a simple JSON protocol which then switches to the SSH stdin/stdout when connected.

Pros/cons:

* Using the ssh2 library was very easy but it was moderately buggy and we are trusting JavaScript developers to get security right which seems risky to put it mildly.
* The Go approach was pretty easy to do and also means you get a binary you can easily use from any language. I trust the Go authors to get SSH right much more than the ssh2 author. Maybe more than the libssh2 authors since so many security errors are memory errors.
* Shelling out to `ssh` has the huge disadvantage that it isn't designed for programmatic access so you end up hackily detecting password prompts and so on using regexes. However it has the huge advantage of supporting all the crazy ways people use SSH - ssh-agent, ProxyCommand, host aliases, etc.

In the end even when using the JS ssh2 library we ended up parsing `.ssh/config` to at least support host aliases.

So yeah, pick your poison - either have something robust that means you'll end up implementing `.ssh/config` manually, or take the hacky option and spend your life dealing with unexpected output differences (foreign languages, modified clients, etc.).

I can post the code for my Go shim if anyone wants.
