### ISSUE TITLE
"[-19] Waiting for USERAUTH response"

### ISSUE THREAD

**Issue by 0xd34b33f** [alexcrichton/ssh2-rs#157]
I'm having such function: 
```rs
fn process_host<A>(hostname: A, command: &str, tx: SyncSender<Response>, agent_mutex: Arc<Mutex<i32>>) -> Response
    where
        A: ToSocketAddrs + Display,
{
    ...
    // Try to authenticate with the first identity in the agent.
    let guard = agent_mutex.lock().unwrap();
    let mut agent = match sess.agent() {
        Ok(a) => a,
        Err(e) => {
            return construct_error(&hostname, start_time, e.to_string(), &tx);
        }
    };
    match agent.connect() {
        Ok(_) => (),
        Err(e) => {
            return construct_error(&hostname, start_time, e.to_string(), &tx);
        }
    };
    if let Err(e) = agent.list_identities() {
        return construct_error(&hostname, start_time, e.to_string(), &tx);
    };
    let id: Vec<Result<PublicKey, Error>> = agent.identities().collect();

    let key = id[0].as_ref().unwrap();
    match agent.userauth("scan", &key) {
        Ok(_) => (),
        Err(e) => return construct_error(&hostname, start_time, e.to_string(), &tx),
    };
    drop(guard);
...
```
It works concurently, nearly 200-2000 threads,
If i'm not using mutex, there're a lot of such errors "[-19] Waiting for USERAUTH response".  So maybe we need to internely synchronize  `agent.userauth` ?

**Comment by wez** [comment]
I suspect that you are overloading the agent; I doubt that it was intended to service hundreds of concurrent requests.

I don't think adding a mutex internally around a muti-step operation in these bindings is the right choice; a mutex makes the most sense to manage internal consistency and not for load management of an external service.

Have you considered using something like a semaphore instead of a mutex to constrain the number of agent requests to a reasonable number?   Another thing for you to consider is whether it makes sense for your application to attempt a bounded number of retries of the agent request.

I'd also suggest that you use `strace` to see what is happening to both the agent and your process.  My gut feeling is that you are exceeding the `listen(2)` backlog for the agent, and the `strace` may help prove/disprove that or surface what is really happening.

**Comment by 0xd34b33f** [comment]
Thank you for so detailed explanation!
