### ISSUE TITLE
Should `Session` be `Clone`?

### ISSUE THREAD

**Issue by spebern** [alexcrichton/ssh2-rs#158]
In `async-ssh2` I currently depend on `Clone` of `Session` so that
I can obtain the `BlockDirection` in `Agent`, `File`, ... .

However I think that exposing `Clone` might not be the best solution,
because people might use the same `Session` to do multiple things
simultaneously.

Another solution might be that every struct `Agent`, `File`, ... gets
its own `blocking_direction` method (maybe everything that has access
to `SessionInner` and then share it via a Trait).

What do you think?

**Comment by wez** [comment]
I think it is OK for `Session` to be `Clone`.  I can add some commentary to the `Session` struct about how the underlying tcp stream is shared between related objects and any cloned handles, and how they are internally synchronized via a mutex, and that if the expectation is for true concurrency multiple tcp streams need to be established and have separate `Session`s wrapped around them.

My thinking on this is that it is more ergonomic for these things to be `Send`, `Sync` and `Clone` than for them not to be, and that the additional complexity of plumbing through something like `blocking_direction` (and presumably other helpers as we discover them) is probably not warranted.  I know they matter to the implementation of async-ssh2, but I don't think they are something you plan to expose to the users of that crate.

The simplicity of cloning the session handle appeals to me.

Would it be helpful for objects that embed/reference the `SessionInner` to also have a method that returns a `Session` object, so that you don't have to explicitly clone it?  Something like this:

```rust
impl Agent {
  pub fn session(&self) -> Session {
     Session { inner: Arc::clone(&self.sess) }
  }
}
```

**Comment by spebern** [comment]
If session stays `Clone` then it is fine and I would not depend on the `session` method.

Adding additional documentation is a good idea :-)
