### ISSUE TITLE
read_dir() doesn't work properly

### ISSUE THREAD

**Issue by crone123** [alexcrichton/ssh2-rs#217]
Hello,
I found a bug in this library. I use it in a homemade backup program and I was surprised that in some folders there was missing files.
So, I investigate my code, and...finally think that the Sftp::read_dir is maybe buggy.
So, I check this, and, finally, the problem is here: (read_dir in File)
https://docs.rs/ssh2/0.9.1/src/ssh2/sftp.rs.html#577-614

Your buffer is on the size of 128 bytes. When I change this size to 4096 (just to try), all my files are seen in the folder.

I think I have understood the problem:
You have a 128 bytes buffer, when you got the "this is too small" error, you upgrade the buffer length.
But, when you got the file again, you got the next file (so you just skipped a file)
And, if this happen many times, you can got folders like mine where you see only 3 files of 24...

Workarround: Set a bigger buffer size.
But, I think there is maybe a better way to fix it, by asking libssh to send the same file name again, and not the next, maybe.
Or maybe there is possible to know in advance the good buffer size.
Or maybe 128bytes is really too small...

But, I let you fix this, because I'm not experienced with libssh in C...

When you push a fix, I can test on my computer to see if, in my test case this is fixed :) (Note: I use the crates.io version)

Thank you :)

**Comment by sourcefrog** [comment]
I think I'm seeing this too, and the diagnosis is plausible. It's easily reproducible by trying to list a directory with long filenames. 

I had a look at the libssh2 C code:

https://github.com/libssh2/libssh2/blob/dba9ad9d3dc99ffcecc90e2b1f538b68f18e0845/src/sftp.c#L1788-L1792

and 

https://github.com/libssh2/libssh2/blob/dba9ad9d3dc99ffcecc90e2b1f538b68f18e0845/src/sftp.c#L1855-L1859

It seems like the most reasonable C API would be to do what Rust ssh2-rs seems to expect: if the buffer is not big enough, return an error, and then the caller can allocate a bigger buffer and try again:

https://github.com/alexcrichton/ssh2-rs/blob/b5ada428daad8c52f70324bb19bd3d02c6a7cbfb/src/sftp.rs#L600-L613

However what the current C code actually seems to do is to return an error and then discard/skip the current entry. I guess this is probably a bug in the C code rather than intentional, since it would affect C clients who don't provide a big enough buffer, too.

Perhaps the Rust code could start out with a much larger buffer, say 64k, to avoid problems?
