### ISSUE TITLE
Thread safety issues

### ISSUE THREAD

**Issue by harmic** [alexcrichton/ssh2-rs#229]
I'm wondering if the way that eg. `sftp::File` (and maybe other) objects are managed is actually correct.

They contain a `raw::LIBSSH2_SFTP_HANDLE` pointer and are protected by a Mutex - but those C structs also contain a pointer to the `raw::LIBSSH2_SFTP` (ie. SFTP session) which in turn contains pointers to the SSH session, etc.

Doesn't this mean that if you send a file to another thread, the corresponding SFTP and SSH session libssh2 structures might be manipulated from multiple threads?

The libssh2 docs say that it is thread safe as long as you "don't share handles simultaneously" - but looking at the code I think that needs to be interpreted as not accessing any handles associated with an SSH2 connection simultaneously.

The reason I am asking about this is that I have an application which uses [`async-ssh2`](https://github.com/spebern/async-ssh2) and I am getting random segfaults and aborts. The aborts point to double free / heap corruption. In all the stack traces I have looked at so far, the crashes occur when closing or dropping `sftp::File` objects, with the crashes themselves originating in low level libssh2 functions.

It seems to me that to make ssh2-rs properly thread-safe we would need to protect all the objects that relate to an SSH2 connection with a single mutex somehow - or do I miss something?

**Comment by emesterhazy** [comment]
From what I recall, libssh2 sessions can only be accessed by one thread at a time. The same restriction applies to all objects derived from a session, such as SFTP file handles, channels, etc. I remember reading through some old mailing list archives and IIRC the conclusion I reached is that you could protect the session with a mutex and then access it and its handles from multiple threads without issues.

However, it is still important that async operations are not interwoven, since calling function B while the future for function A is sleeping will corrupt the internal buffers libssh2 uses for the session. I believe that's what the author of [this blog post](https://jpassing.com/2021/02/31/2021-03-29-building-libssh2-on-windows-lessons-learnt/) is referencing.

When it comes to Rust, this pretty much means that async implementations will need to hold a lock on the session across await points, so a standard Mutex won't work. The alternative is to write non-`Send` objects and run everything for a given session on a single threaded executor.

I need to look into the code again to comment on the specific issue you're pointing out, but if there are session-associated objects that aren't grabbing a lock on the session I'd expect there to be issues.

**Comment by harmic** [comment]
I took another look and I think I made a mistake when first looking at this - in fact the `sftp::File` is protected by locking the session mutex, so should be OK. I think I got confused tracing through what happens when the files are accessed - sorry about that.

I am still getting segfaults & heap corruption though - which should not be possible if ssh2-rs is safely wrapping libssh2, right?

Anyway I will close this issue and see if I can either narrow down the problem, or produce an MRE that I can share.
