### ISSUE TITLE
How to use thread

### ISSUE THREAD

**Issue by gitxpj** [alexcrichton/ssh2-rs#36]
i want use this lib like terminal but use thread tell me this

```
src/main.rs:82:23: 82:36 error: the trait `core::marker::Send` is not implemented for the type `*mut libssh2_sys::LIBSSH2_CHANNEL` [E0277]
src/main.rs:82     let thread_join = thread::spawn(move || {
                                     ^~~~~~~~~~~~~
```

**Comment by alexcrichton** [comment]
Thanks for the report! This is unfortunately because libssh2 itself isn't thread-safe. Channels can't be sent to other threads as the `Session` and all of its derivative objects must be used in the same thread.

To juggle a bunch of channels at once you'll need to use nonblocking I/O instead of blocking I/O unfortunately.

**Comment by gitxpj** [comment]
but i set nonblocking I/O, response error [-37] would block

**Comment by alexcrichton** [comment]
Yeah unfortunately using nonblocking I/O will be a bit more cumbersome as the blocking needs to all be coordinated through elsewhere.
