### ISSUE TITLE
Connection and general performance

### ISSUE THREAD

**Issue by yoni386** [alexcrichton/ssh2-rs#57]
Is there a way how to
Improve performace? I run similar code in golang and rust using this library which is very impressive and in go similar code takes 306-309ms and in rust takes almost dubble around 600ms.  One more thing, in go the rusult is very consistent 306,307,309ms where in rust sometimes it can be 490,550,600ms but most of the time it would be two times more than go code. Could it be related to fact that go is just better language for networking? or the library is using threads and they are not efficient as they are in go?

**Comment by alexcrichton** [comment]
Thanks for the report! Note that this library basically is just a very thin wrapper around libssh2 itself, so the performance is likely all related to libssh2 rather than ssh2-rs (or Rust in general). I'd also recommend to make sure that you're compiling with optimizations (cargo's `--release` flag).

Otherwise if you're still encountering issues I'd recommend filing an upstream bug report at https://github.com/libssh2/libssh2
