### ISSUE TITLE
scp_send stops at 16KB

### ISSUE THREAD

**Issue by opensourcegeek** [alexcrichton/ssh2-rs#79]
All my scp_send requests stop at 16 KB (I'm not sure if it's my code that has an issue). I checked the size of the file I'm writing and it is 1962294272 bytes (about 2GB), could that be the problem?

**Comment by alexcrichton** [comment]
Hm I wonder if this is maybe an accidental integer overflow? In general this library is just a thin wrapper so the issue may be with libssh2?

**Comment by opensourcegeek** [comment]
Gosh, it's actually file.write vs file.write_all issue. So once I swapped the method I'm calling it works fine. Thanks.

**Comment by opensourcegeek** [comment]
Spoke too early, changing to write_all worked on dev machine to dev server. But when we tried against production it failed around 1 MB this time. I initially thought it culd be musl build so tried with gnu libc build it still had the same issue. So currently I've moved it to use SFTP and that seems to consistently write all the data so far. The weird thing with scp_send had different limits based on which server we were pushing data to. Switching to SFTP for now as I don't have a lot of time to debug this issue but it would be good to get to the bottom of it (or at least understand why it fails quietly).

**Comment by crisidev** [comment]
I experienced the same issue you are referring here and I in my case the issue was that I was not disconnecting the channel properly and waiting for transfer completion, so the TCP connection was literally killed before it finished to send all the data.

Example of working code:
```rust
use std::io::prelude::*;
use std::net::TcpStream;
use std::path::Path;
use ssh2::Session;

// Connect to the local SSH server
let tcp = TcpStream::connect("127.0.0.1:22").unwrap();
let mut sess = Session::new().unwrap();
sess.set_tcp_stream(tcp);
sess.handshake().unwrap();
sess.userauth_agent("username").unwrap();

let mut remote_file = sess.scp_send(Path::new("remote"),
                                    0o644, 10, None).unwrap();
remote_file.write_all(b"1234567890").unwrap();

remote_file.send_eof().unwrap();
remote_file.wait_eof().unwrap();
remote_file.close().unwrap();
remote_file.wait_close().unwrap();
```

The magic is in the last 4 lines, where i am actually telling the channel that we are at EOF, waiting for EOF from the server, closing the channel and waiting the channel to be actually closed.

Without the `wait_close()` the underlying TCP/SSH connection can be severed before the file transfer has finished. 

I think this is not really clear in the documentation, but it is not this crate fault IMO.. I had to read a bunch of C code from libssh2 before understanding all this..

**Comment by opensourcegeek** [comment]
@crisidev That's great - thanks for sharing.
